### ISSUE TITLE
Add a License?

### ISSUE THREAD

**Issue by h3po** [baratgabor/GridOS#2]
That's a cool framework you wrote, thanks for publishing it. Could you please add a license to the repo that would officially allow one to upload scripts using your code to the workshop?

**Comment by baratgabor** [comment]
Sure, I'll be adding an MIT licence shortly. 🙂

**Comment by baratgabor** [comment]
Licence added - feel free to publish code using it, if you find it useful. Also, if you need help, like a release version or minified version, just let me know on Discord.

Though, one thing I can't really commit to at this point is API stability, because I think it would still need a lot of work to make sure it's easy and flexible to use with modules.
